<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Scraper/Helper/Simplexml/Autodiscovery.php';

/**
 * Test class for Diggin_Scraper_Helper_Simplexml_Autodiscovery.
 * Generated by PHPUnit on 2009-04-29 at 01:05:51.
 */
class Diggin_Scraper_Helper_Simplexml_AutodiscoveryTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Scraper_Helper_Simplexml_Autodiscovery
     * @access protected
     */
    protected $object;

    protected $html;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        
        $html = <<<HTML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ja" xml:lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="alternate" type="application/rss+xml" title="RSS" href="http://d.hatena.ne.jp/sasezaki/rss">
<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="http://d.hatena.ne.jp/sasezaki/rss2">
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>test</title>
<body>body</body></html>
HTML;


        $dom = new DOMDocument();//DOMDocument::loadHTML($html);
        $dom->loadHTML($html);
        $this->object = new Diggin_Scraper_Helper_Simplexml_Autodiscovery(simplexml_import_dom($dom));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testDirect().
     */
    public function testDirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDiscovery().
     */
    public function testDiscovery()
    {

        //rss check
        $this->assertEquals(
                             array("http://d.hatena.ne.jp/sasezaki/rss", "http://d.hatena.ne.jp/sasezaki/rss2"),
                             $this->object->discovery());

                             
                 $html = <<<HTML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ja" xml:lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>test</title>
<body>body</body></html>
HTML;

        // no link rel
        $dom = new DOMDocument();//DOMDocument::loadHTML($html);
        $dom->loadHTML($html);
        $object = new Diggin_Scraper_Helper_Simplexml_Autodiscovery(simplexml_import_dom($dom));
        
        $this->assertEquals(
                             false,
                             $object->discovery());
        
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
    
    public function testDiscoveryParam()
    {
                $this->assertEquals(
                             false,
                             $this->object->discovery('atom'));
    }
    
    
    /**
     * 
     * <link rel="alternate" type="application/atom+xml" title="Atom" href="http://example.net/atom.xml" />
     * <link rel="alternate" type="application/rss+xml" title="RSS" href="http://example.net/index.rdf" />
     */
}
?>
