<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Scraper/Helper/Simplexml/HeadBaseHref.php';
require_once 'Zend/Uri/Http.php';

/**
 * Test class for Diggin_Scraper_FindHelper_HeadBase.
 * Generated by PHPUnit on 2009-01-18 at 06:25:09.
 */
class Diggin_Scraper_Helper_Simplexml_HeadBaseHrefTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Scraper_FindHelper_HeadBase
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    	$expect = 'http://www2.example.net/terumi/';
            $responseBodyWithHeadTag1 = '<html lang="ja">'.PHP_EOL.
                           '<head>'.PHP_EOL.
                           //'<base href="http://www.example.net/test.cgi?k=v&t=s" />'.
                           "<base href=\"$expect\" />".
                           '<base href="file://var/www/" />'.
                           '</head>'.
                           '<body>'.PHP_EOL.
                           '<a href="test/test.html">testlink</a><br /><br />'.PHP_EOL.
                           '</body>'.PHP_EOL.
                           '</html>';
        
        $simplexml = simplexml_load_string($responseBodyWithHeadTag1);
        
        $this->object = new Diggin_Scraper_Helper_Simplexml_HeadBaseHref($simplexml);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testHeadBase().
     */
    public function testHeadBase() {
        
        $expect = 'http://www2.example.net/terumi/';

        $this->assertEquals(Zend_Uri_Http::fromString($expect),
                            $this->object->getHeadBaseUrl());
                            
                            
        $expect = 'http://www2.example.net/terumi/';
        
        /////////////////////////
        $responseBodyWithNotHead = '<html lang="ja">'.PHP_EOL.
                           '<head>'.PHP_EOL.
                           '</head>'.
                           '<body>'.PHP_EOL.
                           '<a href="test/test.html">testlink</a><br /><br />'.PHP_EOL.
                           '</body>'.PHP_EOL.
                           '</html>';
        
        $simplexml = simplexml_load_string($responseBodyWithNotHead);
        
        $object = new Diggin_Scraper_Helper_Simplexml_HeadBaseHref($simplexml);
        
        $this->assertEquals(false,
                            $object->getHeadBaseUrl());
                            
                            
        ///////////////////////////////////////////////
        
        //str_replace('&',してない場合は実態参照が変換される
        $expect = 'http://www.example.net/test.cgi?k=v&t=a';
        
        /////////////////////////
        $responseBody = <<<HTML
<html>
    <head>
    <title>TERUMI&amp;の部屋</title>
    <base href="http://www.example.net/test.cgi?k=v&amp;t=a" />
    </head>
<body>
神戸では紫芋チップスが流行っています。
</body>
</html>
HTML;
        //
        //$responseBody= str_replace('&', '&amp;', $responseBody);
        $simplexml = simplexml_load_string($responseBody);
        $object = new Diggin_Scraper_Helper_Simplexml_HeadBaseHref($simplexml);
        //$object->setPreAmpFilter(true);
        $t= $object->getHeadBaseUrl();
//        var_export((string)$t);
        $this->assertEquals($expect, (string)$t);
 


        //str_replace('&',している場合は実態参照としてもどる
        $expect = 'http://www.example.net/test.cgi?k=v&amp;t=a';
        
        /////////////////////////
        $responseBody = <<<HTML
<html>
    <head>
    <title>TERUMI&amp;の部屋</title>
    <base href="$expect" />
    </head>
<body>
神戸では紫芋チップスが流行っています。
</body>
</html>
HTML;
        //
        $responseBody= str_replace('&', '&amp;', $responseBody);
        $simplexml = simplexml_load_string($responseBody);
        $object = new Diggin_Scraper_Helper_Simplexml_HeadBaseHref($simplexml);
        $object->setPreAmpFilter(true);
        $t= $object->getHeadBaseUrl();


        //ブラウザ上でのexpect値
$expect = "TERUMI&の部屋";
        
        $simplexml = simplexml_load_string($responseBody);
//        print_r($simplexml);
        $object2 = new Diggin_Scraper_Helper_Simplexml_Title($simplexml);
        
//        print_r($simplexml->asXML());
        
        $this->assertEquals($expect, (string)$object2->direct());

//        $s = new Diggin_Scraper();
//        $scrap = $s->process('//base[@href]', 'title => RAW')
//          ->scrape(array($responseBody));
//        print_r($scrap);
        
        
        
        
        
        
        
                            
        $expect = 'http://www2.example.net/terumi/';
        
    
        $withHeadNotValid = <<<HTML
<html>
    <head>
    <title>TERUMIの部屋</title>
    <base href="file:///Program fils\" />
    <base href="A:\yoshiko\homepage\" />
    <base href="A:\yoshiko\homepage\" />
    </head>
<body>
神戸では紫芋チップスが流行っています。
</body>
</html>
HTML;
        
        $simplexml = simplexml_load_string($withHeadNotValid);
        
        $object = new Diggin_Scraper_Helper_Simplexml_HeadBaseHref($simplexml);
        
        $this->assertEquals(false,
                            $object->getHeadBaseUrl());
        
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
