<?php
require_once 'PHPUnit/Framework.php';

require_once 'Zend/Http/Response.php';
require_once 'Diggin/Scraper/Strategy/Flexible.php';
require_once 'Diggin/Scraper/Process.php';

/**
 * Test class for Diggin_Scraper_Strategy_Flexible.
 * Generated by PHPUnit on 2009-01-18 at 06:23:01.
 */
class Diggin_Scraper_Strategy_Flexible_XpathFlexible_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Scraper_Strategy_Flexible
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @dataProvider toXpathData
     */
    public function test_xpathOrCss2Xpath($exp, $expected)
    {
        $this->assertEquals($expected,
        Diggin_Scraper_Strategy_FlexibleExtForTest::_xpathOrCss2Xpath($exp));
    
    }

    public function toXpathData()
    {
        return array(
                    //is xpath? all node
                    array('.','.'),
                    //array('id("hoge")', 'id("hoge")'),
                    //
                    array('id("hoge")', '//*[@id="hoge"]'),
                    array('id("hoge")//table', '//*[@id="hoge"]//table'),
                    array("id('hoge')", "//*[@id='hoge']"),
                    array('./a','./a'),
                        //is xpah with-start"/" set dot for Simplexml select 
                        //just only current node
                    array('/a', './a'),
                    array('//a', './/a'),
                    //alphabet only quick return
                    array('alpha', './/alpha'),
                    array('E F', './/E//F')
               );
    }
}

class Diggin_Scraper_Strategy_FlexibleExtForTest  extends Diggin_Scraper_Strategy_Flexible
{
    public static function _xpathOrCss2Xpath($exp)
    {
        return parent::_xpathOrCss2Xpath($exp);
    }
}
?>
