<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Scraper.php';
require_once 'Zend/Http/Client.php';
require_once 'Zend/Http/Client/Adapter/Test.php';

/**
 * Test class for Diggin_Scraper.
 * Generated by PHPUnit on 2009-01-16 at 22:23:44.
 */
class Diggin_Scraper_WithFilterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Scraper
     * @access protected
     */
    protected $object;

    private $_responseHeader200 = "HTTP/1.1 200 OK\r\nContent-type: text/html";
    
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Diggin_Scraper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testWithFilter()
    {
        $client = new Zend_Http_Client();
        $clientAdapterTest = new Zend_Http_Client_Adapter_Test();
        $responseBody = <<<BODY
<html><body>123aaaあ</body></html>
BODY;
        $clientAdapterTest->setResponse("$this->_responseHeader200\r\n\r\n$responseBody");
        
        $client->setAdapter($clientAdapterTest);
        $this->object->setHttpClient($client);

        $lambda = create_function('$var', "return \$var.'a';");
        
        //var_dump($lambda);
        
        
        $this->object->process('//body', "digit => TEXT, digits");
        $this->object->process('//body', "lambda => TEXT, digits, $lambda");

        
        $results = $this->object->scrape('http://test.org');
        
        //var_dumP($results);
        
        $this->assertEquals('123', $results['digit']);
        $this->assertEquals('123a', $results['lambda']);
    }
}
?>
