<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Scraper.php';
require_once 'Zend/Http/Client.php';
require_once 'Zend/Http/Client/Adapter/Test.php';

/**
 * Test class for Diggin_Scraper.
 * Generated by PHPUnit on 2009-01-16 at 22:23:44.
 */
class Diggin_Scraper_KouzoutaiHelperTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Scraper
     * @access protected
     */
    protected $object;

    private $_responseHeader200 = "HTTP/1.1 200 OK\r\nContent-type: text/html";
    
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Diggin_Scraper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testKouzoutai()
    {
    	$expectTitle = '>サッカーニュース';
        $html = <<<HTML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ja" xml:lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>$expectTitle</title>
<body>

</body>
</html>
HTML;
require_once 'Zend/Http/Client.php';
require_once 'Zend/Http/Client/Adapter/Test.php';
$adapter = new Zend_Http_Client_Adapter_Test();
$adapter->setResponse(
    "HTTP/1.1 200 OK"        . "\r\n" .
    "Content-type: text/xml" . "\r\n" .
                               "\r\n" .
    $html);
$test = new Zend_Http_Client($url = 'http://www.yahoo.jp', array('adapter' => $adapter));

	
	require_once 'Diggin/Scraper.php';
	$scraper = new Diggin_Scraper();
	$scraper->setHttpClient($test);
	
	$items = new Diggin_Scraper();
	$scraper->scrape("http://localhost/~tobe/news_sample.html");
	$this->assertEquals($expectTitle, $scraper->title());
	$this->assertEquals(false, $scraper->headBaseHref());


    }
}
?>
